from LinkedList import LinkedList

# myList = LinkedList()
# myList.insert(15)
# myList.insert(10)
# myList.insert(5)
# myList.insert(20)
# myList.insert(3)
# myList.insert(2)
# secondList = LinkedList()
# secondList.insert(35)
# secondList.insert(4)
# secondList.insert(18)
# secondList.insert(12)
# print(myList.length())
# print("My first List: ")
# print("After sort: ")
# myList.printList()
# myList.sortList()
# myList.printList()
# print("reversed first List: ")
# myList.reverseList()
# myList.printList()
# print("Second List unsorted: ")
# secondList.printList()
# print("second list sorted: ")
# secondList.sortList()
# secondList.printList()
# secondList.mergeTwoLists(myList.head)
# print("merge myList and secondList: ")
# secondList.printList()
# secondList.sortedInsert(9)
# secondList.printList()
# secondList.delete(13)
# secondList.delete(12)
# print("updated: ")
# secondList.printList()
# secondList.reverseList()
# print("reversed secondList: ")
# secondList.printList()
# palList = LinkedList()
# palList.insert(2)
# palList.insert(3)
# palList.insert(4)
# palList.insert(3)
# palList.insert(2)
# palList.printList()
# if palList.isPalindrome():
#     print("True")
# else:
#     print("False")
# print("before: ")
drakes_list = LinkedList()
drakes_list.insert(55)
drakes_list.insert(73)
drakes_list.insert(28)
drakes_list.insert(17)
drakes_list.insert(21)
drakes_list.printList()
drakes_list.rotate(2)
print("updated: ")
drakes_list.printList()