from LinkedList import LinkedList

myList = LinkedList()
myList.insert(15)
myList.insert(10)
myList.insert(5)
myList.insert(20)
myList.insert(3)
myList.insert(2)
secondList = LinkedList()
secondList.insert(4)
secondList.insert(35)
secondList.insert(12)
secondList.insert(18)
print(myList.length())
print("My first List: ")
myList.printList()
myList.head = myList.sortList(myList.head)
myList.printList()
print("reversed first List: ")
# myList.head.next = myList.reverseList()
myList.head.next = myList.reverseList(myList.head.next)
myList.printList()
secondList.head.next = secondList.sortList(secondList.head.next)
print("second list sorted: ")
secondList.printList()
secondList.head.next = secondList.mergeTwoLists(secondList.head, myList.head)
print("test: ")
secondList.printList()
secondList.sortedInsert(9)
secondList.printList()
secondList.delete(13)
secondList.delete(12)
print("updated: ")
secondList.printList()
secondList.head.next = secondList.reverseList(secondList.head.next)
palList = LinkedList()
palList.insert(2)
palList.insert(3)
palList.insert(4)
palList.insert(3)
palList.insert(2)
print("testing Palindrome")
print("Is list a palindrome? ", palList.isPalindrome())
print("before: ")
secondList.printList()
secondList.rotate(9)
print("updated: ")
secondList.printList()